# Generated by Django 3.2.6 on 2021-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engins', '0003_moto_projet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moto',
            options={'ordering': ['matricule'], 'verbose_name': 'moto et Tricycle', 'verbose_name_plural': 'MOTOS & TRICYCLES'},
        ),
    ]
